# Resolve the version string the app reports and write it into a header.
#
# Run by cmake -P on every build rather than once at configure time: tagging a
# commit, or committing past a tag, changes the answer without touching
# anything CMake would notice, and a binary that names the wrong build is worse
# than no version at all. The header is only rewritten when the string actually
# changes, so the usual build re-runs git and compiles nothing.
#
# Expects SOURCE_DIR and OUTPUT on the command line.

# What a build with no tag to describe reports. Deliberately not
# project(... VERSION ...): that number names the release the packages carry,
# and a binary that cannot find the tag it came from has no business claiming
# it. 0.0.0 is no release at all, sorts below every real one, and is a version
# nobody has to look up to recognise as meaning "unknown build".
set(version "0.0.0")

# --match keeps this to the tags release.yml recognises, so a `nightly` or a
# moving `latest` pointing at some other commit cannot name the build. --dirty
# is the point of doing this at all: an uncommitted tree that reports the tag
# verbatim is exactly the bug report nobody can reproduce.
find_package(Git QUIET)
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --tags --dirty --match "v[0-9]*"
        WORKING_DIRECTORY ${SOURCE_DIR}
        OUTPUT_VARIABLE described
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE status)
    # A failure here is a checkout with no tag in it -- a source tarball, a
    # shallow clone, the container build in scripts/build-deb.sh that drops
    # .git -- and not something to fail a build over. It leaves the version
    # above, which says exactly that.
    if(status EQUAL 0)
        string(REGEX REPLACE "^v" "" version "${described}")
    endif()
endif()

string(CONCAT header
    "// Generated by cmake/version.cmake. Do not edit.\n"
    "#pragma once\n"
    "#define CORELET_VERSION \"${version}\"\n")

set(previous "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL header)
    file(WRITE "${OUTPUT}" "${header}")
    message(STATUS "corelet ${version}")
endif()
